# Generated by Django 5.2 on 2025-04-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('donation', '0002_funds_fundtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='fund_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='donation.funds'),
        ),
    ]
