# Generated by Django 5.2 on 2025-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
