# Generated by Django 5.2 on 2025-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyRequest', '0002_alter_emergencyrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='emergency_contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
