# Generated by Django 5.2 on 2025-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('program_description', models.TextField()),
                ('program_organizer', models.CharField(max_length=255)),
                ('program_conductor', models.CharField(max_length=255)),
                ('program_skills', models.CharField(choices=[('leading', 'Leading'), ('first aid', 'First Aid')], max_length=50)),
                ('program_location', models.CharField(max_length=255)),
                ('program_seats', models.IntegerField(default=0)),
                ('program_seats_available', models.IntegerField(default=0)),
                ('program_start_date', models.DateTimeField()),
                ('program_end_date', models.DateTimeField()),
                ('program_duration', models.TimeField()),
            ],
        ),
    ]
