# # Generated by Django 5.2 on 2025-04-29 15:31

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('program', '0001_initial'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='program',
#             name='program_duration',
#             field=models.IntegerField(),
#         ),
#     ]


# Generated by Django 5.2 on 2025-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE program_program
                ALTER COLUMN program_duration TYPE integer
                USING EXTRACT(EPOCH FROM program_duration) / 60;
            """,
            reverse_sql="""
                ALTER TABLE program_program
                ALTER COLUMN program_duration TYPE time
                USING (program_duration || ' minutes')::interval;
            """,
        ),
    ]
