# Generated by Django 5.2 on 2025-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_program_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_seats_available',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_skills',
        ),
        migrations.AddField(
            model_name='program',
            name='program_skills',
            field=models.ManyToManyField(related_name='programs', to='program.skill'),
        ),
    ]
