# Generated by Django 5.2 on 2025-04-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_skill_remove_program_program_seats_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_skills',
        ),
        migrations.AddField(
            model_name='program',
            name='program_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='program.skill'),
        ),
    ]
