# Generated by Django 5.2 on 2025-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_remove_program_program_skills_program_program_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_duration',
            field=models.IntegerField(),
        ),
    ]
