# Generated by Django 5.2 on 2025-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Wildfire', 'Wildfire'), ('Hurricane', 'Hurricane'), ('Tornado', 'Tornado')], max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('magnitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('affected_people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Recovering', 'Recovering'), ('Resolved', 'Resolved'), ('Contained', 'Contained')], max_length=20)),
                ('description', models.TextField()),
                ('casualties', models.PositiveIntegerField()),
                ('damage_cost', models.BigIntegerField()),
            ],
        ),
    ]
