# Generated by Django 5.2 on 2025-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
