# Generated by Django 5.2 on 2025-04-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_awards',
            field=models.CharField(choices=[('SUPPORTER', 'Supporter'), ('ROOKIE', 'Rookie'), ('CHAMPION', 'Champion'), ('VISIONARY', 'Visionary'), ('LEGEND', 'Legend')], default='SUPPORTER', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_last_donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_total_donate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
