# Generated by Django 5.2 on 2025-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
        ('volunteer', '0002_volunteerjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='completed_missions',
            field=models.ManyToManyField(blank=True, related_name='volunteers_completed_mission', to='mission.mission'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='joined_missions',
            field=models.ManyToManyField(blank=True, related_name='volunteers_joined_mission', to='mission.mission'),
        ),
    ]
