# Generated by Django 5.2 on 2025-05-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('instructor', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField()),
                ('enrolled', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('certification', models.CharField(max_length=150)),
                ('cost', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Almost Full', 'Almost Full'), ('Full', 'Full')], max_length=20)),
                ('skills', models.ManyToManyField(related_name='courses', to='workshop.skill')),
            ],
        ),
    ]
