# Generated by Django 5.2 on 2025-05-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_course_participants_coursejoinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled',
        ),
    ]
