# Generated by Django 5.2 on 2025-05-01 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='amount_needed',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
