# Generated by Django 5.2 on 2025-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('volunteers_needed', models.IntegerField()),
                ('volunteers_joined', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('coordinator', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('lives_can_be_saved', models.IntegerField(default=0)),
            ],
        ),
    ]
