# Generated by Django 5.2 on 2025-05-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
        ('volunteer', '0003_volunteerprofile_completed_missions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='mission.mission')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_requests', to='volunteer.volunteerprofile')),
            ],
            options={
                'unique_together': {('volunteer', 'mission')},
            },
        ),
    ]
